# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        c-compiler: [gcc-10, clang]
        cxx-compiler: [g++-10, clang++]
        cmake-build-type: [DEBUG, RELEASE]
        include:
          - { c-compiler: gcc-10, cxx-compiler: g++10, ... }
          - { c-compiler: clang, cxx-compiler: clang++, ... }

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install compilers
      run: sudo apt install gcc-10 g++-10 clang

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      with:
        cmakeBuildType: Debug
        buildDirectory: ${{ github.workspace }}/build
      env:
        CC:   ${{ matrix.c-compiler }}
        CXX:  ${{ matrix.cxx-compiler }}
        CMAKE_BUILD_TYPE: ${{ matrix.cmake-build-type }}
        
    - name: run-tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -VV
